"""Post-incident report generation in multiple formats."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Optional

from .incident import (
    Incident,
    STEP_DONE,
    STEP_SKIPPED,
    STEP_IN_PROGRESS,
    STEP_PENDING,
    STATUS_RESOLVED,
    STATUS_OPEN,
)


# ----- Helpers ----------------------------------------------------------------


def _fmt_duration(seconds: float) -> str:
    secs = int(seconds)
    h, rem = divmod(secs, 3600)
    m, s = divmod(rem, 60)
    if h:
        return f"{h}h {m}m {s}s"
    if m:
        return f"{m}m {s}s"
    return f"{s}s"


def _fmt_ts(iso: Optional[str]) -> str:
    if not iso:
        return "—"
    dt = datetime.fromisoformat(iso)
    return dt.strftime("%Y-%m-%d %H:%M:%S UTC")


def _sla_badge(step) -> str:
    if step.sla_minutes is None:
        return ""
    if step.status in (STEP_DONE, STEP_SKIPPED) and step.duration_seconds() is not None:
        dur = step.duration_seconds()
        if dur <= step.sla_minutes * 60:
            return " ✅"
        else:
            over = int(dur - step.sla_minutes * 60)
            return f" ❌ (SLA +{_fmt_duration(over)} over)"
    elif step.sla_breached():
        return " ⚠️ SLA BREACH"
    return f" (SLA: {step.sla_minutes}m)"


# ----- Markdown ---------------------------------------------------------------


def to_markdown(incident: Incident) -> str:
    done, total = incident.progress()
    elapsed = _fmt_duration(incident.elapsed_seconds())
    breached = incident.breached_steps()
    status_emoji = {"open": "U0001f534", "resolved": "✅", "cancelled": "U0001f6ab"}.get(
        incident.status, ""
    )

    lines = [
        f"# Post-Incident Report: {incident.id}",
        "",
        f"**Runbook:** {incident.runbook_name}  ",
        f"**Severity:** {incident.severity}  ",
        f"**Category:** {incident.category}  ",
        f"**Status:** {status_emoji} {incident.status.upper()}  ",
        f"**Created:** {_fmt_ts(incident.created_at)}  ",
        f"**Resolved:** {_fmt_ts(incident.resolved_at)}  ",
        f"**Total elapsed:** {elapsed}  ",
        f"**Steps completed:** {done}/{total}  ",
    ]

    if incident.escalation_contact:
        lines.append(f"**Escalation contact:** {incident.escalation_contact}  ")

    if incident.description:
        lines += ["", f"> {incident.description}"]

    if incident.resolution_notes:
        lines += ["", "## Resolution Notes", "", incident.resolution_notes]

    if breached:
        lines += [
            "",
            "## ⚠️ SLA Breaches",
            "",
            f"{len(breached)} step(s) exceeded their SLA target:",
            "",
        ]
        for s in breached:
            dur = s.duration_seconds()
            over_str = ""
            if dur is not None:
                over = dur - (s.sla_minutes or 0) * 60
                over_str = f" (+{_fmt_duration(over)} over SLA)"
            lines.append(f"- **{s.title}** (team: {s.team}){over_str}")

    lines += ["", "## Step Timeline", ""]
    lines += ["| # | Step | Team | Status | Duration | SLA |", "|---|------|------|--------|----------|-----|"]

    for i, step in enumerate(incident.steps, 1):
        dur_str = "—"
        if step.duration_seconds() is not None:
            dur_str = _fmt_duration(step.duration_seconds())
        sla_str = f"{step.sla_minutes}m" if step.sla_minutes else "—"
        emoji = {
            STEP_DONE: "✅", STEP_SKIPPED: "⏭️",
            STEP_IN_PROGRESS: "U0001f504", STEP_PENDING: "⏳"
        }.get(step.status, step.status)
        lines.append(
            f"| {i} | {step.title} | {step.team} | {emoji} {step.status} | {dur_str} | {sla_str} |"
        )

    notes_steps = [s for s in incident.steps if s.notes]
    if notes_steps:
        lines += ["", "## Step Notes", ""]
        for s in notes_steps:
            lines.append(f"**{s.title}:** {s.notes}")

    lines += [
        "",
        "---",
        "",
        "*Generated by [IT Incident Commander](https://github.com/intruderfr/it-incident-commander)*  ",
        f"*Author: Aslam Ahamed — Head of IT @ Prestige One Developments, Dubai*",
    ]

    return "\n".join(lines)


# ----- Plain text -------------------------------------------------------------


def to_text(incident: Incident) -> str:
    done, total = incident.progress()
    elapsed = _fmt_duration(incident.elapsed_seconds())
    sep = "─" * 60

    lines = [
        sep,
        f"  POST-INCIDENT REPORT  —  {incident.id}",
        sep,
        f"  Runbook   : {incident.runbook_name}",
        f"  Severity  : {incident.severity}",
        f"  Category  : {incident.category}",
        f"  Status    : {incident.status.upper()}",
        f"  Created   : {_fmt_ts(incident.created_at)}",
        f"  Resolved  : {_fmt_ts(incident.resolved_at)}",
        f"  Elapsed   : {elapsed}",
        f"  Progress  : {done}/{total} steps",
    ]
    if incident.escalation_contact:
        lines.append(f"  Escalation: {incident.escalation_contact}")
    lines.append(sep)

    if incident.resolution_notes:
        lines += ["", "RESOLUTION NOTES", "", f"  {incident.resolution_notes}", ""]

    breached = incident.breached_steps()
    if breached:
        lines += ["SLA BREACHES", ""]
        for s in breached:
            dur = s.duration_seconds()
            over = ""
            if dur is not None:
                over_s = dur - (s.sla_minutes or 0) * 60
                over = f" (+{_fmt_duration(over_s)} over SLA)"
            lines.append(f"  ⚠  {s.title} ({s.team}){over}")
        lines.append("")

    lines += ["STEP TIMELINE", ""]
    for i, step in enumerate(incident.steps, 1):
        symbol = {
            STEP_DONE: "[✓]", STEP_SKIPPED: "[→]",
            STEP_IN_PROGRESS: "[~]", STEP_PENDING: "[ ]"
        }.get(step.status, "[?]")
        dur_str = ""
        if step.duration_seconds() is not None:
            dur_str = f"  {_fmt_duration(step.duration_seconds())}"
        sla_str = _sla_badge(step)
        lines.append(f"  {i:2}. {symbol} {step.title}  ({step.team}){dur_str}{sla_str}")
        if step.notes:
            lines.append(f"        Note: {step.notes}")

    lines += ["", sep]
    return "\n".join(lines)


# ----- JSON -------------------------------------------------------------------


def to_json(incident: Incident, indent: int = 2) -> str:
    return json.dumps(incident.to_dict(), indent=indent)
